### ISSUE TITLE
Detected wrong "participants"

### ISSUE THREAD

**Issue by biejay** [BryceStevenWilley/visioning_texts#19]
Using **german layout on android** gives me:

`WARNING: only 2 participants are supported at the moment, we parsed multiple:
math.js:130 
(3) ["Tim", "Tom", "Nachrichten"]
0: "Tim"
1: "Tom"
2: "Nachrichten"
length: 3
__proto__: Array(0)`

My **format** looks like this (maybe this helps):
![Unbenannt](https://user-images.githubusercontent.com/8942784/72797049-b32f0c80-3c40-11ea-8be4-3453d45d84e3.JPG)

With another chat it also gave me 4 "participants". And when i set my phone to USA then it didn't say "Nachrichten" but "Messages" as 3 participant.

**Comment by htkcodes** [comment]
I think because its reading per line, make sure each message is in a single line, the exporter might export some messages badly.

**Comment by biejay** [comment]
@htkcodes Hm would appreciate a fix that handles these extra lines because i got a ton of these in my conversations :D 
Maybe by filtering the date format and therefore detect a new message.

**Comment by BryceStevenWilley** [comment]
So I think this issue happens because WhatsApp will occasionally include a line that goes something like "Message to this chat are now secured with end to end encrpytion".  It looks exactly like normal message line, but won't include a colon between the participant name and the body of the message.  I think it can be solved with some stricter parsing, which I'll try to add tonight

**Comment by BryceStevenWilley** [comment]
The fix should be in @biejay, let me know if it fixes it for you!

**Comment by biejay** [comment]
Works! Thank you mate @BryceStevenWilley .
