### ISSUE TITLE
Emoji's are cut-off in visualization

### ISSUE THREAD

**Issue by towfiqueA** [BryceStevenWilley/visioning_texts#35]
Screenshots below.

The emoji's get cut-off on the sides, bottom, and top. I can manually inspect the page, change the width and height, which resolves the bottom and right side. However, I don't know how I could resolve the cut-offs on the left side and the top. Any suggestions are appreciated.

![image](https://user-images.githubusercontent.com/61135261/74628363-caafc700-5112-11ea-9699-b9d873c734ed.png)

![image](https://user-images.githubusercontent.com/61135261/74628378-d13e3e80-5112-11ea-8242-683712cacf16.png)

**Comment by sukhinsergey** [comment]
Same issue here.

**Comment by BryceStevenWilley** [comment]
Sorry, for the lateness, I was using a very poor heuristic for sizing the emoji's, and wasn't actually putting a cap on the max size. Both of those should be fixed with https://github.com/BryceStevenWilley/visioning_texts/commit/253d2ffabdb3872850e40c2c6ffc1178c0f2dcf6, so feel free to give it a try and see if it fixes it for you!
